### ISSUE TITLE
There is no postinstall.js

### ISSUE THREAD

**Issue by CREEATION** [maliMirkec/starter-project#2]
Is the readme outdated? 🤔
I'm guessing this is obsolete now with `starter-project-cli`?

> After the installation, run the following command to set up the project:
> 
> `node node_modules/starter-package/postinstall.js`

**Comment by maliMirkec** [comment]
@CREEATION Yes, you are correct. I would update the docs very soon.

**Comment by maliMirkec** [comment]
@CREEATION Fixed! Try installing the latest version, then run `node node_modules/starter-project/postinstall.js` (there was also a typo in the command), and finally run `gulp` to see the project in your browser. Let me know if it works!

**Comment by maliMirkec** [comment]
I am closing this for lack of feedback.
